service: jobcan

provider:
  name: aws
  region: ap-northeast-1
  runtime: java8
  iamRoleARN:

package:
  artifact: target/scala-2.11/beat-can.jar

functions:
  beat:
    handler: com.github.hideto0710.beat_can.Beat::handleRequest
    events:
      - http:
          path: working
          method: post
      - http:
          path: working
          method: delete
